import { QueryRunner } from "typeorm";
import { SeederBase } from "./seederBase";
import * as bcrypt from 'bcrypt';
import { marcasSeed } from "../data/marcasSeed";
import { usersSeed } from "../data/usersSeed";
import { modelosSeed } from "../data/modelosSeed";

export class schemaPublicFillEstados extends SeederBase{

    name = 'schemaPublicSeed';
    
    public async up(queryRunner: QueryRunner): Promise<void> {
        
        /*await queryRunner.query(`CREATE TABLE "public"."users" ("id" character varying NOT NULL, "email" text NOT NULL, "password" text NOT NULL, "fullname" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "roles" text array NOT NULL DEFAULT '{user}', "compania" text NOT NULL, "schema" text NOT NULL, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "public"."marcas" ("id" character varying NOT NULL, "nombre" character varying(30) NOT NULL, "createdAtUserId" character varying, "updatedAtUserId" character varying, CONSTRAINT "PK_0dabf9ed9a15bfb634cb675f7d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "public"."modelos" ("id" character varying NOT NULL, "nombre" character varying(30) NOT NULL, "createdAtUserId" character varying, "updatedAtUserId" character varying, "id_marca" character varying, CONSTRAINT "PK_e9df275f890167381d41c793603" PRIMARY KEY ("id"))`);        
        await queryRunner.query(`ALTER TABLE "marcas" ADD CONSTRAINT "FK_cc334a4a2cfeaafc117a20d786c" FOREIGN KEY ("createdAtUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "marcas" ADD CONSTRAINT "FK_3de0c44151ac67964db5b3ffa28" FOREIGN KEY ("updatedAtUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modelos" ADD CONSTRAINT "FK_1f6acf02ce5dc127cefd83ce512" FOREIGN KEY ("createdAtUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modelos" ADD CONSTRAINT "FK_4159889f9d2e9b0f639555a656a" FOREIGN KEY ("updatedAtUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modelos" ADD CONSTRAINT "FK_164a7416c55ff4a7c9e74d9d896" FOREIGN KEY ("id_marca") REFERENCES "marcas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        */        
        
        await queryRunner.query(`
            CREATE TABLE "public"."paises" (
                "clave" character varying NOT NULL,
                "nombre" character varying NOT NULL,
                CONSTRAINT "PK_pais_clave" PRIMARY KEY ("clave")
            );`
        );

        await queryRunner.query(`
            INSERT INTO public.paises (clave, nombre) VALUES
                ('001', 'méxico')
        `)

        await queryRunner.query(`
            CREATE TABLE "public"."estados" (
                "clave" character varying NOT NULL, 
                "nombre" character varying NOT NULL,
                "clave_pais" character varying NOT NULL,
                CONSTRAINT "PK_estado_clave" PRIMARY KEY ("clave", "clave_pais")
            );`
        );

        await queryRunner.query(`
            INSERT INTO public.estados (clave, nombre, clave_pais) VALUES
                ('01', 'aguascalientes', '01'),
                ('02', 'baja california', '01'),
                ('03', 'baja california Sur', '01'),
                ('04', 'campeche', '01'),
                ('05', 'coahuila', '01'),
                ('06', 'colima', '01'),
                ('07', 'chiapas', '01'),
                ('08', 'chihuahua', '01'),
                ('09', 'ciudad de méxico', '01'),
                ('10', 'durango', '01'),
                ('11', 'guanajuato', '01'),
                ('12', 'guerrero', '01'),
                ('13', 'hidalgo', '01'),
                ('14', 'jalisco', '01'),
                ('15', 'méxico', '01'),
                ('16', 'michoacán', '01'),
                ('17', 'morelos', '01'),
                ('18', 'nayarit', '01'),
                ('19', 'nuevo león', '01'),
                ('20', 'oaxaca', '01'),
                ('21', 'puebla', '01'),
                ('22', 'querétaro', '01'),
                ('23', 'quintana roo', '01'),
                ('24', 'san luis potosí', '01'),
                ('25', 'sinaloa', '01'),
                ('26', 'sonora', '01'),
                ('27', 'tabasco', '01'),
                ('28', 'tamaulipas', '01'),
                ('29', 'tlaxcala', '01'),
                ('30', 'veracruz', '01'),
                ('31', 'yucatán', '01'),
                ('32', 'zacatecas', '01'),
        `)

        await queryRunner.query(`
            CREATE TABLE "public"."municipios" (
                "clave" character varying NOT NULL, 
                "nombre" character varying NOT NULL,
                "clave_estado" varying NOT NULL
                CONSTRAINT "PK_municipio_clave" PRIMARY KEY ("clave", "clave_estado")
            );`
        );

        await queryRunner.query(`
            INSERT INTO public.municipios (clave, nombre, clave_estado) VALUES
                ('001', 'ahome', '25'),
                ('002', 'angostura', '25'),
                ('003', 'badiraguato', '25'),
                ('004', 'concordia', '25'),
                ('005', 'cosalá', '25'),
                ('006', 'culiacán', '25'),
                ('007', 'choix', '25'),
                ('008', 'elota', '25'),
                ('009', 'escuinapa', '25'),
                ('010', 'el fuerte', '25'),
                ('011', 'guasave', '25'),
                ('012', 'mazatlán', '25'),
                ('013', 'mocorito', '25'),
                ('014', 'rosario', '25'),
                ('015', 'salvador alvarado', '25'),
                ('016', 'san ignacio', '25'),
                ('017', 'sinaloa', '25'),
                ('018', 'navolato', '25'),
                ('019', 'eldorado', '25'),
                ('020', 'juan josé ríos', '25');
        `)


        await queryRunner.query(`
            insert into public.municipios (clave, nombre, clave_estado) values
                ('001', 'ensenada', '01'),
                ('002', 'mexicali', '01'),
                ('003', 'tecate', '01'),
                ('004', 'tijuana', '01'),
                ('005', 'playas de rosarito', '01'),
                ('006', 'san quintín', '01'),
                ('007', 'san felipe', '01');
        `)

            
        await queryRunner.query(`
            insert into public.municipios (clave, nombre, clave_estado) values
                ('001', 'comondú', '03'),
                ('002', 'mulegé', '03'),
                ('003', 'la paz', '03'),
                ('004', 'los cabos', '03'),
                ('005', 'loreto', '03');
        `)

        await queryRunner.query(`
            insert into public.municipios (clave, nombre, clave_estado) values
                ('002', 'azcapotzalco', '09'),
                ('003', 'coyoacán', '09'),
                ('004', 'cuajimalpa de morelos', '09'),
                ('005', 'gustavo a. madero', '09'),
                ('006', 'iztacalco', '09'),
                ('007', 'iztapalapa', '09'),
                ('008', 'la magdalena contreras', '09'),
                ('009', 'milpa alta', '09'),
                ('010', 'álvaro obregón', '09'),
                ('011', 'tláhuac', '09'),
                ('012', 'tlalpan', '09'),
                ('013', 'xochimilco', '09'),
                ('014', 'benito juárez', '09'),
                ('015', 'cuauhtémoc', '09'),
                ('016', 'miguel hidalgo', '09'),
                ('017', 'venustiano carranza', '09');
        `)
        
        await queryRunner.query(`
            insert into public.municipios (clave, nombre, clave_estado) values
                ('001', 'canatlán', '10'),
                ('002', 'canelas', '10'),
                ('003', 'coneto de comonfort', '10'),
                ('004', 'cuencamé', '10'),
                ('005', 'durango', '10'),
                ('006', 'general simón bolívar', '10'),
                ('007', 'gómez palacio', '10'),
                ('008', 'guadalupe victoria', '10'),
                ('009', 'guanaceví', '10'),
                ('010', 'hidalgo', '10'),
                ('011', 'indé', '10'),
                ('012', 'lerdo', '10'),
                ('013', 'mapimí', '10'),
                ('014', 'mezquital', '10'),
                ('015', 'nazas', '10'),
                ('016', 'nombre de dios', '10'),
                ('017', 'ocampo', '10'),
                ('018', 'el oro', '10'),
                ('019', 'otáez', '10'),
                ('020', 'pánuco de coronado', '10'),
                ('021', 'peñón blanco', '10'),
                ('022', 'poanas', '10'),
                ('023', 'pueblo nuevo', '10'),
                ('024', 'rodeo', '10'),
                ('025', 'san bernardo', '10'),
                ('026', 'san dimas', '10'),
                ('027', 'san juan de guadalupe', '10'),
                ('028', 'san juan del río', '10'),
                ('029', 'san luis del cordero', '10'),
                ('030', 'san pedro del gallo', '10'),
                ('031', 'santa clara', '10'),
                ('032', 'santiago papasquiaro', '10'),
                ('033', 'súchil', '10'),
                ('034', 'tamazula', '10'),
                ('035', 'tepehuanes', '10'),
                ('036', 'tlahualilo', '10'),
                ('037', 'topia', '10'),
                ('038', 'vicente guerrero', '10'),
                ('039', 'nuevo ideal', '10');
        `)

        await queryRunner.query(`
            insert into public.municipios (clave, nombre, clave_estado) values
                ('001', 'acatic', '14'),
                ('002', 'acatlán de juárez', '14'),
                ('003', 'ahualulco de mercado', '14'),
                ('004', 'amacueca', '14'),
                ('005', 'amatitán', '14'),
                ('006', 'ameca', '14'),
                ('007', 'san juanito de escobedo', '14'),
                ('008', 'arandas', '14'),
                ('009', 'el arenal', '14'),
                ('010', 'atemajac de brizuela', '14'),
                ('011', 'atengo', '14'),
                ('012', 'atenguillo', '14'),
                ('013', 'atotonilco el alto', '14'),
                ('014', 'atoyac', '14'),
                ('015', 'autlán de navarro', '14'),
                ('016', 'ayotlán', '14'),
                ('017', 'ayutla', '14'),
                ('018', 'la barca', '14'),
                ('019', 'bolaños', '14'),
                ('020', 'cabo corrientes', '14'),
                ('021', 'casimiro castillo', '14'),
                ('022', 'cihuatlán', '14'),
                ('023', 'zapotlán el grande', '14'),
                ('024', 'cocula', '14'),
                ('025', 'colotlán', '14'),
                ('026', 'concepción de buenos aires', '14'),
                ('027', 'cuautitlán de garcía barragán', '14'),
                ('028', 'cuautla', '14'),
                ('029', 'cuquío', '14'),
                ('030', 'chapala', '14'),
                ('031', 'chimaltitán', '14'),
                ('032', 'chiquilistlán', '14'),
                ('033', 'degollado', '14'),
                ('034', 'ejutla', '14'),
                ('035', 'encarnación de díaz', '14'),
                ('036', 'etzatlán', '14'),
                ('037', 'el grullo', '14'),
                ('038', 'guachinango', '14'),
                ('039', 'guadalajara', '14'),
                ('040', 'hostotipaquillo', '14'),
                ('041', 'huejúcar', '14'),
                ('042', 'huejuquilla el alto', '14'),
                ('043', 'la huerta', '14'),
                ('044', 'ixtlahuacán de los membrillos', '14'),
                ('045', 'ixtlahuacán del río', '14'),
                ('046', 'jalostotitlán', '14'),
                ('047', 'jamay', '14'),
                ('048', 'jesús maría', '14'),
                ('049', 'jilotlán de los dolores', '14'),
                ('050', 'jocotepec', '14'),
                ('051', 'juanacatlán', '14'),
                ('052', 'juchitlán', '14'),
                ('053', 'lagos de moreno', '14'),
                ('054', 'el limón', '14'),
                ('055', 'magdalena', '14'),
                ('056', 'santa maría del oro', '14'),
                ('057', 'la manzanilla de la paz', '14'),
                ('058', 'mascota', '14'),
                ('059', 'mazamitla', '14'),
                ('060', 'mexticacán', '14'),
                ('061', 'mezquitic', '14'),
                ('062', 'mixtlán', '14'),
                ('063', 'ocotlán', '14'),
                ('064', 'ojuelos de jalisco', '14'),
                ('065', 'pihuamo', '14'),
                ('066', 'poncitlán', '14'),
                ('067', 'puerto vallarta', '14'),
                ('068', 'villa purificación', '14'),
                ('069', 'quitupan', '14'),
                ('070', 'el salto', '14'),
                ('071', 'san cristóbal de la barranca', '14'),
                ('072', 'san diego de alejandría', '14'),
                ('073', 'san juan de los lagos', '14'),
                ('074', 'san julián', '14'),
                ('075', 'san marcos', '14'),
                ('076', 'san martín de bolaños', '14'),
                ('077', 'san martín hidalgo', '14'),
                ('078', 'san miguel el alto', '14'),
                ('079', 'gómez farías', '14'),
                ('080', 'san sebastián del oeste', '14'),
                ('081', 'santa maría de los ángeles', '14'),
                ('082', 'sayula', '14'),
                ('083', 'tala', '14'),
                ('084', 'talpa de allende', '14'),
                ('085', 'tamazula de gordiano', '14'),
                ('086', 'tapalpa', '14'),
                ('087', 'tecalitlán', '14'),
                ('088', 'tecolotlán', '14'),
                ('089', 'techaluta de montenegro', '14'),
                ('090', 'tenamaxtlán', '14'),
                ('091', 'teocaltiche', '14'),
                ('092', 'teocuitatlán de corona', '14'),
                ('093', 'tepatitlán de morelos', '14'),
                ('094', 'tequila', '14'),
                ('095', 'teuchitlán', '14'),
                ('096', 'tizapán el alto', '14'),
                ('097', 'tlajomulco de zúñiga', '14'),
                ('098', 'tlaquepaque', '14'),
                ('099', 'tolimán', '14'),
                ('100', 'tomatlán', '14'),
                ('101', 'tonalá', '14'),
                ('102', 'tonaya', '14'),
                ('103', 'tonila', '14'),
                ('104', 'totatiche', '14'),
                ('105', 'tototlán', '14'),
                ('106', 'tuxcacuesco', '14'),
                ('107', 'tuxcueca', '14'),
                ('108', 'tuxpan', '14'),
                ('109', 'unión de san antonio', '14'),
                ('110', 'unión de tula', '14'),
                ('111', 'valle de guadalupe', '14'),
                ('112', 'valle de juárez', '14'),
                ('113', 'san gabriel', '14'),
                ('114', 'villa corona', '14'),
                ('115', 'villa guerrero', '14'),
                ('116', 'villa hidalgo', '14'),
                ('117', 'cañadas de obregón', '14'),
                ('118', 'yahualica de gonzález gallo', '14'),
                ('119', 'zacoalco de torres', '14'),
                ('120', 'zapopan', '14'),
                ('121', 'zapotiltic', '14'),
                ('122', 'zapotitlán de vadillo', '14'),
                ('123', 'zapotlán del rey', '14'),
                ('124', 'zapotlanejo', '14'),
                ('125', 'san ignacio cerro gordo', '14');
        `)

        await queryRunner.query(`
            insert into public.municipios (clave, nombre, clave_estado) values
                ('001', 'acambay de ruiz castañeda', '15'),
                ('002', 'acolman', '15'),
                ('003', 'aculco', '15'),
                ('004', 'almoloya de alquisiras', '15'),
                ('005', 'almoloya de juárez', '15'),
                ('006', 'almoloya del río', '15'),
                ('007', 'amanalco', '15'),
                ('008', 'amatepec', '15'),
                ('009', 'amecameca', '15'),
                ('010', 'apaxco', '15'),
                ('011', 'atenco', '15'),
                ('012', 'atizapán', '15'),
                ('013', 'atizapán de zaragoza', '15'),
                ('014', 'atlacomulco', '15'),
                ('015', 'atlautla', '15'),
                ('016', 'axapusco', '15'),
                ('017', 'ayapango', '15'),
                ('018', 'calimaya', '15'),
                ('019', 'capulhuac', '15'),
                ('020', 'coacalco de berriozábal', '15'),
                ('021', 'coatepec harinas', '15'),
                ('022', 'cocotitlán', '15'),
                ('023', 'coyotepec', '15'),
                ('024', 'cuautitlán', '15'),
                ('025', 'chalco', '15'),
                ('026', 'chapa de mota', '15'),
                ('027', 'chapultepec', '15'),
                ('028', 'chiautla', '15'),
                ('029', 'chicoloapan', '15'),
                ('030', 'chiconcuac', '15'),
                ('031', 'chimalhuacán', '15'),
                ('032', 'donato guerra', '15'),
                ('033', 'ecatepec de morelos', '15'),
                ('034', 'ecatzingo', '15'),
                ('035', 'huehuetoca', '15'),
                ('036', 'hueypoxtla', '15'),
                ('037', 'huixquilucan', '15'),
                ('038', 'isidro fabela', '15'),
                ('039', 'ixtapaluca', '15'),
                ('040', 'ixtapan de la sal', '15'),
                ('041', 'ixtapan del oro', '15'),
                ('042', 'ixtlahuaca', '15'),
                ('043', 'xalatlaco', '15'),
                ('044', 'jaltenco', '15'),
                ('045', 'jilotepec', '15'),
                ('046', 'jilotzingo', '15'),
                ('047', 'jiquipilco', '15'),
                ('048', 'jocotitlán', '15'),
                ('049', 'joquicingo', '15'),
                ('050', 'juchitepec', '15'),
                ('051', 'lerma', '15'),
                ('052', 'malinalco', '15'),
                ('053', 'melchor ocampo', '15'),
                ('054', 'metepec', '15'),
                ('055', 'mexicaltzingo', '15'),
                ('056', 'morelos', '15'),
                ('057', 'naucalpan de juárez', '15'),
                ('058', 'nezahualcóyotl', '15'),
                ('059', 'nextlalpan', '15'),
                ('060', 'nicolás romero', '15'),
                ('061', 'nopaltepec', '15'),
                ('062', 'ocoyoacac', '15'),
                ('063', 'ocuilan', '15'),
                ('064', 'el oro', '15'),
                ('065', 'otumba', '15'),
                ('066', 'otzoloapan', '15'),
                ('067', 'otzolotepec', '15'),
                ('068', 'ozumba', '15'),
                ('069', 'papalotla', '15'),
                ('070', 'la paz', '15'),
                ('071', 'polotitlán', '15'),
                ('072', 'rayón', '15'),
                ('073', 'san antonio la isla', '15'),
                ('074', 'san felipe del progreso', '15'),
                ('075', 'san josé del rincón', '15'),
                ('076', 'san martín de las pirámides', '15'),
                ('077', 'san mateo atenco', '15'),
                ('078', 'san simón de guerrero', '15'),
                ('079', 'santo tomás', '15'),
                ('080', 'soyaniquilpan de juárez', '15'),
                ('081', 'sultepec', '15'),
                ('082', 'tecámac', '15'),
                ('083', 'tejupilco', '15'),
                ('084', 'temamatla', '15'),
                ('085', 'temascalapa', '15'),
                ('086', 'temascalcingo', '15'),
                ('087', 'temascaltepec', '15'),
                ('088', 'temoaya', '15'),
                ('089', 'tenancingo', '15'),
                ('090', 'tenango del aire', '15'),
                ('091', 'tenango del valle', '15'),
                ('092', 'teoloyucán', '15'),
                ('093', 'teotihuacán', '15'),
                ('094', 'tepetlaoxtoc', '15'),
                ('095', 'tepetlixpa', '15'),
                ('096', 'tepotzotlán', '15'),
                ('097', 'tequixquiac', '15'),
                ('098', 'texcaltitlán', '15'),
                ('099', 'texcalyacac', '15'),
                ('100', 'texcoco', '15'),
                ('101', 'tezoyuca', '15'),
                ('102', 'tianguistenco', '15'),
                ('103', 'timilpan', '15'),
                ('104', 'tlalmanalco', '15'),
                ('105', 'tlalnepantla de baz', '15'),
                ('106', 'tlatlaya', '15'),
                ('107', 'toluca', '15'),
                ('108', 'tonatico', '15'),
                ('109', 'tultepec', '15'),
                ('110', 'tultitlán', '15'),
                ('111', 'valle de bravo', '15'),
                ('112', 'valle de chalco solidaridad', '15'),
                ('113', 'villa de allende', '15'),
                ('114', 'villa del carbón', '15'),
                ('115', 'villa guerrero', '15'),
                ('116', 'villa victoria', '15'),
                ('117', 'xonacatlán', '15'),
                ('118', 'zacazonapan', '15'),
                ('119', 'zacualpan', '15'),
                ('120', 'zinacantepec', '15'),
                ('121', 'zumpahuacán', '15'),
                ('122', 'zumpango', '15'),
                ('123', 'cuautitlán izcalli', '15'),
                ('124', 'luvianos', '15'),
                ('125', 'tonanitla', '15');
        `)




        await queryRunner.query(`
            insert into public.municipios (clave, nombre, clave_estado) values
                ('001', 'abasolo', '19'),
                ('002', 'agualeguas', '19'),
                ('003', 'los aldamas', '19'),
                ('004', 'allende', '19'),
                ('005', 'anáhuac', '19'),
                ('006', 'apodaca', '19'),
                ('007', 'aramberri', '19'),
                ('008', 'bustamante', '19'),
                ('009', 'cadereyta jiménez', '19'),
                ('010', 'el carmen', '19'),
                ('011', 'cerralvo', '19'),
                ('012', 'ciénega de flores', '19'),
                ('013', 'china', '19'),
                ('014', 'doctor arroyo', '19'),
                ('015', 'doctor coss', '19'),
                ('016', 'doctor gonzález', '19'),
                ('017', 'galeana', '19'),
                ('018', 'garcía', '19'),
                ('019', 'san pedro garza garcía', '19'),
                ('020', 'general bravo', '19'),
                ('021', 'general escobedo', '19'),
                ('022', 'general terán', '19'),
                ('023', 'general treviño', '19'),
                ('024', 'general zaragoza', '19'),
                ('025', 'general zuazua', '19'),
                ('026', 'guadalupe', '19'),
                ('027', 'los herreras', '19'),
                ('028', 'higueras', '19'),
                ('029', 'hualahuises', '19'),
                ('030', 'iturbide', '19'),
                ('031', 'juárez', '19'),
                ('032', 'lampazos de naranjo', '19'),
                ('033', 'linares', '19'),
                ('034', 'marín', '19'),
                ('035', 'melchor ocampo', '19'),
                ('036', 'mier y noriega', '19'),
                ('037', 'mina', '19'),
                ('038', 'montemorelos', '19'),
                ('039', 'monterrey', '19'),
                ('040', 'parás', '19'),
                ('041', 'pesquería', '19'),
                ('042', 'los ramones', '19'),
                ('043', 'rayones', '19'),
                ('044', 'sabinas hidalgo', '19'),
                ('045', 'salinas victoria', '19'),
                ('046', 'san nicolás de los garza', '19'),
                ('047', 'hidalgo', '19'),
                ('048', 'santa catarina', '19'),
                ('049', 'santiago', '19'),
                ('050', 'vallecillo', '19'),
                ('051', 'villaldama', '19'),
                ('052', 'colombia', '19');
        `)

        await queryRunner.query(`
            insert into public.municipios (clave, nombre, clave_estado) values
                ('001', 'amealco de bonfil', '22'),
                ('002', 'pinal de amoles', '22'),
                ('003', 'arroyo seco', '22'),
                ('004', 'cadereyta de montes', '22'),
                ('005', 'colón', '22'),
                ('006', 'corregidora', '22'),
                ('007', 'ezequiel montes', '22'),
                ('008', 'huimilpan', '22'),
                ('009', 'jalpan de serra', '22'),
                ('010', 'landa de matamoros', '22'),
                ('011', 'el marqués', '22'),
                ('012', 'pedro escobedo', '22'),
                ('013', 'peñamiller', '22'),
                ('014', 'querétaro', '22'),
                ('015', 'san joaquín', '22'),
                ('016', 'san juan del río', '22'),
                ('017', 'tequisquiapan', '22'),
                ('018', 'tolimán', '22');
        `)

  

    }    
}
